name: optifit
channels:
  - conda-forge
  - bioconda
  - defaults
  - r
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=0_gnu
  - _r-mutex=1.0.1=anacondar_1
  - aioeasywebdav=2.4.0=py37_1000
  - aiohttp=3.6.1=py37h516909a_0
  - appdirs=1.4.3=py_1
  - async-timeout=3.0.1=py_1000
  - attrs=19.3.0=py_0
  - bcrypt=3.1.7=py37h516909a_0
  - binutils_impl_linux-64=2.36.1=h193b22a_2
  - binutils_linux-64=2.36=hf3e587d_33
  - biom-format=2.1.8=py37hc1659b7_0
  - biopython=1.76=py37h516909a_0
  - blast-legacy=2.2.26=2
  - boost=1.74.0=py37h6dcda5c_3
  - boost-cpp=1.74.0=h9359b55_0
  - boto3=1.10.27=py_0
  - botocore=1.13.27=py_0
  - bwidget=1.9.13=0
  - bzip2=1.0.8=h516909a_1
  - c-ares=1.16.1=h516909a_3
  - ca-certificates=2021.10.8=ha878542_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - cachetools=3.1.1=py_0
  - cairo=1.16.0=h488836b_1006
  - certifi=2021.10.8=py37h89c1867_1
  - cffi=1.13.2=py37h8022711_0
  - chardet=3.0.4=py37_1003
  - click=7.1.2=pyh9f0ad1d_0
  - configargparse=0.13.0=py_1
  - cryptography=2.8=py37h72c5cf5_0
  - curl=7.71.1=he644dc0_8
  - datrie=0.8=py37h516909a_0
  - decorator=4.4.1=py_0
  - docutils=0.15.2=py37_0
  - dropbox=9.4.0=py_0
  - expat=2.2.5=he1b5a44_1004
  - fftw=3.3.10=nompi_hcdd671c_101
  - filechunkio=1.8=py_2
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=2.001=hab24e00_0
  - font-ttf-source-code-pro=2.030=hab24e00_0
  - font-ttf-ubuntu=0.83=hab24e00_0
  - fontconfig=2.13.1=h1056068_1002
  - fonts-conda-forge=1=0
  - freetype=2.10.4=he06d7ca_0
  - fribidi=1.0.10=h516909a_0
  - ftputil=3.4=py_0
  - future=0.18.2=py37hc8dfbb8_2
  - gcc_impl_linux-64=9.3.0=h6df7d76_17
  - gcc_linux-64=9.3.0=hf25ea35_33
  - gdk-pixbuf=2.36.12=haf2c3b9_1004
  - gettext=0.19.8.1=hc5be6a0_1002
  - gfortran_impl_linux-64=9.3.0=hc4a2995_19
  - gfortran_linux-64=9.3.0=hdc58fab_33
  - ghostscript=9.22=hf484d3e_1001
  - giflib=5.2.1=h516909a_2
  - gitdb2=2.0.6=py_0
  - gitpython=3.0.5=py_0
  - glib=2.66.2=he1b5a44_0
  - gmp=6.2.0=h58526e2_4
  - gobject-introspection=1.58.2=py37h5503ade_1002
  - google-api-core=1.14.3=py37_0
  - google-auth=1.7.1=py_0
  - google-cloud-core=1.0.3=py_0
  - google-cloud-storage=1.23.0=py37_0
  - google-resumable-media=0.5.0=py_0
  - googleapis-common-protos=1.6.0=py37_0
  - graphite2=1.3.13=hf484d3e_1000
  - graphviz=2.42.3=h0511662_0
  - gsl=2.6=h294904e_0
  - gxx_impl_linux-64=9.3.0=hbdd7822_17
  - gxx_linux-64=9.3.0=h3fbe746_33
  - h5py=3.3.0=nompi_py37ha3df211_100
  - harfbuzz=2.7.2=hb1ce69c_1
  - hdf5=1.10.6=nompi_h7c3c948_1111
  - icu=67.1=he1b5a44_0
  - idna=2.8=py37_1000
  - imagemagick=7.0.10_28=pl526h201ca68_0
  - importlib_metadata=0.23=py37_0
  - jbig=2.1=h14c3975_2001
  - jinja2=2.10.3=py_0
  - jmespath=0.9.4=py_0
  - jpeg=9d=h516909a_0
  - jsonschema=3.2.0=py37_0
  - kernel-headers_linux-64=2.6.32=he073ed8_14
  - krb5=1.17.1=hfafb76e_3
  - ld_impl_linux-64=2.36.1=hea4e1c9_2
  - libblas=3.9.0=12_linux64_openblas
  - libcblas=3.9.0=12_linux64_openblas
  - libcroco=0.6.13=h8d621e5_0
  - libcurl=7.71.1=hcdd3856_8
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=h516909a_1
  - libffi=3.2.1=he1b5a44_1006
  - libgcc-devel_linux-64=9.3.0=hb95220a_17
  - libgcc-ng=11.1.0=hc902ee8_6
  - libgfortran-ng=9.4.0=h69a702a_11
  - libgfortran4=7.5.0=hae1eefd_17
  - libgfortran5=9.4.0=h62347ff_11
  - libgit2=1.1.1=h3974521_0
  - libglib=2.66.2=h0dae87d_0
  - libgomp=11.1.0=hc902ee8_6
  - libiconv=1.16=h516909a_0
  - liblapack=3.9.0=12_linux64_openblas
  - libnghttp2=1.41.0=h8cfc5f6_2
  - libopenblas=0.3.18=pthreads_h8fe5266_0
  - libpng=1.6.37=hed695b0_0
  - libprotobuf=3.11.0=h8b12597_0
  - librsvg=2.50.1=h33a7fed_0
  - libssh2=1.9.0=hab1572f_5
  - libstdcxx-devel_linux-64=9.3.0=hf0c5c8d_17
  - libstdcxx-ng=11.1.0=h56837e0_6
  - libtiff=4.2.0=hbd63e13_2
  - libtool=2.4.6=h14c3975_1002
  - libuuid=2.32.1=h14c3975_1000
  - libwebp=1.2.0=h3452ae3_0
  - libwebp-base=1.2.0=h7f98852_2
  - libxcb=1.13=h14c3975_1002
  - libxml2=2.9.10=h68273f3_2
  - lz4-c=1.9.3=h9c3ff4c_1
  - make=4.2.1=h14c3975_2004
  - markupsafe=1.1.1=py37h516909a_0
  - more-itertools=7.2.0=py_0
  - mothur=1.46.1=h7165306_0
  - mpfr=4.0.2=he80fd80_1
  - mpi=1.0=mpich
  - mpich=3.4.2=h846660c_100
  - multidict=4.5.2=py37h14c3975_1000
  - ncbi-ngs-sdk=2.10.4=h3e72335_1
  - ncurses=6.2=he1b5a44_2
  - networkx=2.4=py_0
  - numpy=1.18.5=py37h8960a57_0
  - openjpeg=2.3.1=h981e76c_2
  - openssl=1.1.1l=h7f98852_0
  - pandas=1.0.5=py37h0da4684_0
  - pandoc=2.14.2=h7f98852_0
  - pango=1.42.4=h80147aa_5
  - paramiko=2.6.0=py37_0
  - pcre=8.44=he1b5a44_0
  - pcre2=10.36=h032f7d1_1
  - perl=5.26.2=h516909a_1006
  - perl-app-cpanminus=1.7044=pl526_1
  - perl-business-isbn=3.004=pl526_0
  - perl-business-isbn-data=20140910.003=pl526_0
  - perl-carp=1.38=pl526_3
  - perl-constant=1.33=pl526_1
  - perl-data-dumper=2.173=pl526_0
  - perl-encode=2.88=pl526_1
  - perl-exporter=5.72=pl526_1
  - perl-extutils-makemaker=7.36=pl526_1
  - perl-file-path=2.16=pl526_0
  - perl-file-temp=0.2304=pl526_2
  - perl-mime-base64=3.15=pl526_1
  - perl-parent=0.236=pl526_1
  - perl-uri=1.76=pl526_0
  - perl-xml-libxml=2.0132=pl526h7ec2d77_1
  - perl-xml-namespacesupport=1.12=pl526_0
  - perl-xml-sax=1.02=pl526_0
  - perl-xml-sax-base=1.09=pl526_0
  - perl-xsloader=0.24=pl526_0
  - pixman=0.38.0=h516909a_1003
  - pkg-config=0.29.2=h14c3975_1005
  - poppler=0.65.0=h14e79db_0
  - poppler-data=0.4.10=0
  - prettytable=0.7.2=py_3
  - protobuf=3.11.0=py37he1b5a44_0
  - psutil=5.6.7=py37h516909a_0
  - pthread-stubs=0.4=h14c3975_1001
  - pyasn1=0.4.8=py_0
  - pyasn1-modules=0.2.7=py_0
  - pycparser=2.19=py37_1
  - pygments=2.4.2=py_0
  - pygraphviz=1.6=py37h04d21ab_1
  - pynacl=1.3.0=py37h516909a_1001
  - pyopenssl=19.0.0=py37_0
  - pyrsistent=0.15.6=py37h516909a_0
  - pysftp=0.2.9=py_1
  - pysocks=1.7.1=py37_0
  - python=3.7.3=h357f687_2
  - python-dateutil=2.8.0=py_0
  - python-irodsclient=0.7.0=py_0
  - python_abi=3.7=1_cp37m
  - pytz=2019.3=py_0
  - pyyaml=5.1.2=py37h516909a_0
  - r=4.0=r40_1004
  - r-askpass=1.1=r40hcdcec82_2
  - r-assertthat=0.2.1=r40h6115d3f_2
  - r-backports=1.1.10=r40hcdcec82_0
  - r-base=4.0.3=ha43b4e8_3
  - r-base64enc=0.1_3=r40hcdcec82_1004
  - r-bitops=1.0_7=r40hcfec24a_0
  - r-blob=1.2.1=r40h6115d3f_1
  - r-boot=1.3_25=r40h6115d3f_1
  - r-brew=1.0_6=r40hc72bb7e_1003
  - r-brio=1.1.0=r40h9e2df91_1
  - r-broom=0.7.9=r40hc72bb7e_0
  - r-cachem=1.0.6=r40hcfec24a_0
  - r-callr=3.7.0=r40hc72bb7e_0
  - r-cellranger=1.1.0=r40h6115d3f_1003
  - r-class=7.3_17=r40hcdcec82_1
  - r-cli=3.0.1=r40h03ef668_1
  - r-clipr=0.7.1=r40h142f84f_0
  - r-cluster=2.1.0=r40h31ca83e_4
  - r-codetools=0.2_17=r40h142f84f_0
  - r-colorspace=1.4_1=r40hcdcec82_2
  - r-commonmark=1.7=r40hcfec24a_1002
  - r-covr=3.5.1=r40h0357c0b_0
  - r-cowplot=1.1.1=r40hc72bb7e_0
  - r-cpp11=0.2.3=r40h142f84f_1
  - r-crayon=1.4.1=r40hc72bb7e_0
  - r-credentials=1.3.1=r40hc72bb7e_0
  - r-crosstalk=1.1.1=r40hc72bb7e_0
  - r-curl=4.3=r40hcdcec82_1
  - r-data.table=1.14.2=r40hcfec24a_0
  - r-dbi=1.1.0=r40h6115d3f_1
  - r-dbplyr=2.1.1=r40hc72bb7e_0
  - r-desc=1.2.0=r40h6115d3f_1003
  - r-devtools=2.4.2=r40hc72bb7e_0
  - r-diagram=1.6.5=r40hb0f4dca_0
  - r-diagrammer=1.0.6.1=r40hc72bb7e_0
  - r-diffobj=0.3.2=r40h9e2df91_1
  - r-digest=0.6.27=r40h1b71b39_0
  - r-downloader=0.4=r40hc72bb7e_1003
  - r-dplyr=1.0.7=r40h03ef668_0
  - r-dt=0.19=r40hc72bb7e_0
  - r-dtplyr=1.1.0=r40hc72bb7e_0
  - r-ellipsis=0.3.2=r40hcfec24a_0
  - r-evaluate=0.14=r40h6115d3f_2
  - r-fansi=0.4.1=r40hcdcec82_1
  - r-farver=2.0.3=r40h0357c0b_1
  - r-fastmap=1.1.0=r40h03ef668_0
  - r-forcats=0.5.1=r40hc72bb7e_0
  - r-foreign=0.8_80=r40hcdcec82_0
  - r-formatr=1.11=r40hc72bb7e_0
  - r-fs=1.5.0=r40h0357c0b_0
  - r-gargle=1.2.0=r40hc72bb7e_0
  - r-generics=0.1.0=r40hc72bb7e_0
  - r-gert=1.3.2=r40hbd84cd2_0
  - r-ggforce=0.3.3=r40h03ef668_0
  - r-ggplot2=3.3.5=r40hc72bb7e_0
  - r-ggraph=2.0.5=r40h03ef668_0
  - r-ggrepel=0.9.1=r40h03ef668_0
  - r-ggtext=0.1.1=r40hc72bb7e_0
  - r-gh=1.3.0=r40hc72bb7e_0
  - r-git2r=0.28.0=r40hf628c3e_0
  - r-gitcreds=0.1.1=r40hc72bb7e_0
  - r-glue=1.4.2=r40hcdcec82_0
  - r-googledrive=2.0.0=r40hc72bb7e_0
  - r-googlesheets4=1.0.0=r40h785f33e_0
  - r-graphlayouts=0.7.1=r40h03ef668_0
  - r-gridextra=2.3=r40hc72bb7e_1003
  - r-gridtext=0.1.4=r40h03ef668_0
  - r-gtable=0.3.0=r40h6115d3f_3
  - r-haven=2.3.1=r40hde08347_0
  - r-here=0.1=r40h6115d3f_1003
  - r-highr=0.8=r40h6115d3f_2
  - r-hms=1.1.1=r40hc72bb7e_0
  - r-htmltools=0.5.0=r40h0357c0b_0
  - r-htmlwidgets=1.5.3=r40hc72bb7e_0
  - r-httpuv=1.6.1=r40h03ef668_0
  - r-httr=1.4.2=r40h6115d3f_0
  - r-ids=1.0.1=r40hc72bb7e_1
  - r-igraph=1.2.6=r40h084b37e_1
  - r-influencer=0.1.0=r40hcfec24a_1004
  - r-ini=0.3.1=r40hc72bb7e_1003
  - r-isoband=0.2.2=r40h0357c0b_0
  - r-jpeg=0.1_8.1=r40hcfec24a_1
  - r-jquerylib=0.1.4=r40hc72bb7e_0
  - r-jsonlite=1.7.2=r40hcfec24a_0
  - r-kernsmooth=2.23_18=r40h7679c2e_0
  - r-knitr=1.30=r40h6115d3f_0
  - r-labeling=0.4.2=r40h142f84f_0
  - r-later=1.2.0=r40h03ef668_0
  - r-lattice=0.20_41=r40hcdcec82_2
  - r-lazyeval=0.2.2=r40hcdcec82_2
  - r-lifecycle=1.0.1=r40hc72bb7e_0
  - r-lubridate=1.7.10=r40h03ef668_0
  - r-magick=2.7.2=r40h03ef668_0
  - r-magrittr=2.0.1=r40hcfec24a_1
  - r-markdown=1.1=r40hcdcec82_1
  - r-mass=7.3_53=r40hcdcec82_0
  - r-matrix=1.2_18=r40h7fa42b6_3
  - r-memoise=2.0.0=r40hc72bb7e_0
  - r-mgcv=1.8_33=r40h7fa42b6_0
  - r-mime=0.9=r40hcdcec82_1
  - r-modelr=0.1.8=r40h6115d3f_0
  - r-munsell=0.5.0=r40h6115d3f_1003
  - r-nlme=3.1_150=r40h31ca83e_0
  - r-nnet=7.3_14=r40hcdcec82_1
  - r-openssl=1.4.3=r40he5c4762_0
  - r-patchwork=1.1.1=r40hc72bb7e_0
  - r-pillar=1.6.4=r40hc72bb7e_0
  - r-pkgbuild=1.2.0=r40hc72bb7e_0
  - r-pkgconfig=2.0.3=r40h6115d3f_1
  - r-pkgload=1.2.1=r40h03ef668_0
  - r-plogr=0.2.0=r40h6115d3f_1003
  - r-plyr=1.8.6=r40h0357c0b_1
  - r-png=0.1_7=r40hcfec24a_1004
  - r-polyclip=1.10_0=r40h0357c0b_2
  - r-praise=1.0.0=r40h6115d3f_1004
  - r-prettyunits=1.1.1=r40h6115d3f_1
  - r-processx=3.5.2=r40hcfec24a_0
  - r-progress=1.2.2=r40h6115d3f_2
  - r-promises=1.2.0.1=r40h03ef668_0
  - r-ps=1.4.0=r40h0eb13af_0
  - r-purrr=0.3.4=r40hcdcec82_1
  - r-r6=2.5.0=r40hc72bb7e_0
  - r-rappdirs=0.3.3=r40hcfec24a_0
  - r-rcmdcheck=1.4.0=r40h785f33e_0
  - r-rcolorbrewer=1.1_2=r40h6115d3f_1003
  - r-rcpp=1.0.4.6=r40h0357c0b_1
  - r-rcpparmadillo=0.10.6.0.0=r40h306847c_0
  - r-rcppeigen=0.3.3.9.1=r40h306847c_0
  - r-rcurl=1.98_1.2=r40hcdcec82_1
  - r-readr=1.4.0=r40h1b71b39_0
  - r-readxl=1.3.1=r40hde08347_4
  - r-recommended=4.0=r40_1004
  - r-rematch=1.0.1=r40h6115d3f_1003
  - r-rematch2=2.1.2=r40h6115d3f_1
  - r-remotes=2.4.1=r40hc72bb7e_0
  - r-reprex=2.0.1=r40hc72bb7e_0
  - r-reshape2=1.4.4=r40h0357c0b_1
  - r-reticulate=1.20=r40h03ef668_0
  - r-rex=1.2.0=r40hc72bb7e_1
  - r-rgexf=0.16.0=r40hc72bb7e_1
  - r-rlang=0.4.12=r40hcfec24a_0
  - r-rmarkdown=2.5=r40h142f84f_0
  - r-roxygen2=7.1.2=r40h03ef668_0
  - r-rpart=4.1_15=r40hcdcec82_2
  - r-rprojroot=1.3_2=r40h6115d3f_1003
  - r-rstudioapi=0.13=r40hc72bb7e_0
  - r-rversions=2.1.1=r40hc72bb7e_0
  - r-rvest=1.0.2=r40hc72bb7e_0
  - r-scales=1.1.1=r40h6115d3f_0
  - r-schtools=0.1.0=r40hc72bb7e_0
  - r-selectr=0.4_2=r40h6115d3f_1
  - r-servr=0.22=r40hc72bb7e_0
  - r-sessioninfo=1.1.1=r40hc72bb7e_1002
  - r-shape=1.4.6=r40ha770c72_0
  - r-spatial=7.3_12=r40hcdcec82_1
  - r-stringi=1.5.3=r40h604b29c_0
  - r-stringr=1.4.0=r40h6115d3f_2
  - r-survival=3.2_7=r40hcdcec82_0
  - r-sys=3.4=r40hcdcec82_0
  - r-systemfonts=1.0.2=r40hef9c87a_0
  - r-testthat=3.0.0=r40he524a50_0
  - r-tibble=3.1.5=r40hcfec24a_0
  - r-tidygraph=1.2.0=r40h0357c0b_0
  - r-tidyr=1.1.4=r40h03ef668_0
  - r-tidyselect=1.1.0=r40h6115d3f_0
  - r-tidyverse=1.3.1=r40hc72bb7e_0
  - r-tiff=0.1_8=r40hcfec24a_0
  - r-tinytex=0.27=r40hc72bb7e_0
  - r-tweenr=1.0.2=r40h03ef668_0
  - r-usethis=2.1.2=r40hc72bb7e_0
  - r-utf8=1.1.4=r40hcdcec82_1003
  - r-uuid=0.1_4=r40hcfec24a_1
  - r-vctrs=0.3.8=r40hcfec24a_1
  - r-viridis=0.6.1=r40hc72bb7e_0
  - r-viridislite=0.3.0=r40h6115d3f_1003
  - r-visnetwork=2.0.9=r40hc72bb7e_1
  - r-waldo=0.2.2=r40hc72bb7e_0
  - r-whisker=0.4=r40h6115d3f_1
  - r-withr=2.3.0=r40h6115d3f_0
  - r-xfun=0.19=r40h9e2df91_0
  - r-xml=3.99_0.6=r40hcfec24a_0
  - r-xml2=1.3.2=r40h0357c0b_1
  - r-xopen=1.0.0=r40hc72bb7e_1003
  - r-yaml=2.2.1=r40hcdcec82_1
  - r-zeallot=0.1.0=r40h6115d3f_1002
  - r-zip=2.2.0=r40hcfec24a_0
  - ratelimiter=1.2.0=py37_1000
  - readline=8.1=h46c0cb4_0
  - requests=2.22.0=py37_1
  - rsa=4.0=py_0
  - s3transfer=0.2.1=py37_0
  - scipy=1.7.1=py37hf2a6cf1_0
  - sed=4.8=hbfbb72e_0
  - six=1.13.0=py37_0
  - smmap2=2.0.5=py_0
  - snakemake=5.5.4=2
  - snakemake-minimal=5.5.4=py_2
  - sqlite=3.33.0=h4cf870e_1
  - sra-tools=2.10.0=pl526he1b5a44_0
  - sysroot_linux-64=2.12=he073ed8_14
  - tectonic=0.3.3=h024be4f_0
  - tk=8.6.10=hed695b0_0
  - tktable=2.10=h555a92e_3
  - urllib3=1.25.7=py37_0
  - vsearch=2.15.2=h95f258a_1
  - wrapt=1.11.2=py37h516909a_0
  - xmlrunner=1.7.7=py_0
  - xorg-kbproto=1.0.7=h14c3975_1002
  - xorg-libice=1.0.10=h516909a_0
  - xorg-libsm=1.2.3=h84519dc_1000
  - xorg-libx11=1.6.9=h516909a_0
  - xorg-libxau=1.0.9=h14c3975_0
  - xorg-libxdmcp=1.1.3=h516909a_0
  - xorg-libxext=1.3.4=h516909a_0
  - xorg-libxpm=3.5.12=h516909a_1002
  - xorg-libxrender=0.9.10=h516909a_1002
  - xorg-libxt=1.1.5=h516909a_1003
  - xorg-renderproto=0.11.1=h14c3975_1002
  - xorg-xextproto=7.3.0=h14c3975_1002
  - xorg-xproto=7.0.31=h14c3975_1007
  - xz=5.2.5=h516909a_1
  - yaml=0.1.7=h14c3975_1001
  - yarl=1.3.0=py37h14c3975_1000
  - zipp=0.6.0=py_0
  - zlib=1.2.11=h516909a_1006
  - zstd=1.4.9=ha95c52a_0
  - pip:
    - pip==20.2.4
    - setuptools==50.3.2
    - wheel==0.35.1
prefix: /home/sovacool/bin/miniconda3/envs/optifit
