name: qiime2-2019.10
channels:
- qiime2/label/r2019.10
- conda-forge
- bioconda
- defaults
dependencies:
- _libgcc_mutex
- _r-mutex
- alsa-lib
- arb-bio-tools
- asn1crypto
- atomicwrites
- attrs
- backcall
- bibtexparser
- binutils_impl_linux-64
- binutils_linux-64
- bioconductor-biobase
- bioconductor-biocgenerics
- bioconductor-biocparallel
- bioconductor-biostrings
- bioconductor-dada2
- bioconductor-delayedarray
- bioconductor-genomeinfodb
- bioconductor-genomeinfodbdata
- bioconductor-genomicalignments
- bioconductor-genomicranges
- bioconductor-iranges
- bioconductor-rsamtools
- bioconductor-s4vectors
- bioconductor-shortread
- bioconductor-summarizedexperiment
- bioconductor-xvector
- bioconductor-zlibbioc
- biom-format
- blas
- blast
- bleach
- bokeh
- boost
- boost-cpp
- bwidget
- bzip2
- ca-certificates
- cachecontrol
- cairo
- certifi
- cffi
- chardet
- click
- cryptography
- curl
- cutadapt
- cycler
- cython
- dbus
- deblur
- decorator
- defusedxml
- dendropy
- dnaio
- emperor
- entrypoints
- expat
- fastcluster
- fasttree
- fontconfig
- freetype
- future
- gcc_impl_linux-64
- gcc_linux-64
- gettext
- gfortran_impl_linux-64
- gfortran_linux-64
- giflib
- glib
- gmp
- gneiss
- gnutls
- graphite2
- gsl
- gst-plugins-base
- gstreamer
- gxx_impl_linux-64
- gxx_linux-64
- h5py
- harfbuzz
- hdf5
- hdmedians
- hmmer
- icu
- idna
- ijson
- importlib_metadata
- ipykernel
- ipython
- ipython_genutils
- ipywidgets
- iqtree
- jedi
- jinja2
- joblib
- jpeg
- jsonschema
- jupyter_client
- jupyter_core
- kiwisolver
- krb5
- lcms2
- libarbdb
- libblas
- libcblas
- libcurl
- libedit
- libffi
- libgcc
- libgcc-ng
- libgfortran-ng
- libiconv
- liblapack
- liblapacke
- libopenblas
- libpng
- libsodium
- libssh2
- libstdcxx-ng
- libtiff
- libuuid
- libxcb
- libxml2
- lockfile
- lz4-c
- mafft
- make
- markupsafe
- matplotlib
- matplotlib-base
- mistune
- more-itertools
- msgpack-python
- natsort
- nbconvert
- nbformat
- ncurses
- nettle
- networkx
- nose
- notebook
- numpy
- olefile
- openjdk
- openssl
- packaging
- pandas
- pandoc
- pandocfilters
- pango
- parso
- patsy
- pcre
- perl
- perl-archive-tar
- perl-carp
- perl-common-sense
- perl-compress-raw-bzip2
- perl-compress-raw-zlib
- perl-exporter
- perl-exporter-tiny
- perl-extutils-makemaker
- perl-io-compress
- perl-io-zlib
- perl-json
- perl-json-xs
- perl-list-moreutils
- perl-list-moreutils-xs
- perl-pathtools
- perl-scalar-list-utils
- perl-types-serialiser
- perl-xsloader
- pexpect
- pickleshare
- pigz
- pillow
- pip
- pixman
- pluggy
- prometheus_client
- prompt_toolkit
- psutil
- pthread-stubs
- ptyprocess
- py
- pycparser
- pygments
- pyopenssl
- pyparsing
- pyqt
- pyrsistent
- pysocks
- pytest
- python
- python-dateutil
- pytz
- pyyaml
- pyzmq
- q2-alignment
- q2-composition
- q2-cutadapt
- q2-dada2
- q2-deblur
- q2-demux
- q2-diversity
- q2-emperor
- q2-feature-classifier
- q2-feature-table
- q2-fragment-insertion
- q2-gneiss
- q2-longitudinal
- q2-metadata
- q2-phylogeny
- q2-quality-control
- q2-quality-filter
- q2-sample-classifier
- q2-taxa
- q2-types
- q2-vsearch
- q2cli
- q2templates
- qiime2
- qt
- r-assertthat
- r-backports
- r-base
- r-bh
- r-bitops
- r-cli
- r-cluster
- r-colorspace
- r-crayon
- r-data.table
- r-digest
- r-ellipsis
- r-fansi
- r-formatr
- r-futile.logger
- r-futile.options
- r-ggplot2
- r-glue
- r-gtable
- r-hwriter
- r-labeling
- r-lambda.r
- r-lattice
- r-latticeextra
- r-lazyeval
- r-magrittr
- r-mass
- r-matrix
- r-matrixstats
- r-mgcv
- r-munsell
- r-nlme
- r-permute
- r-pillar
- r-pkgconfig
- r-plyr
- r-r6
- r-rcolorbrewer
- r-rcpp
- r-rcppparallel
- r-rcurl
- r-reshape2
- r-rlang
- r-scales
- r-snow
- r-stringi
- r-stringr
- r-tibble
- r-utf8
- r-vctrs
- r-vegan
- r-viridislite
- r-withr
- r-zeallot
- raxml
- readline
- requests
- scikit-bio
- scikit-learn
- scipy
- seaborn
- send2trash
- sepp
- setuptools
- sina
- sip
- six
- sortmerna
- sqlite
- statsmodels
- tbb
- terminado
- testpath
- tk
- tktable
- tornado
- traitlets
- tzlocal
- unifrac
- urllib3
- vsearch
- wcwidth
- webencodings
- wheel
- widgetsnbextension
- xopen
- xorg-fixesproto
- xorg-inputproto
- xorg-kbproto
- xorg-libice
- xorg-libsm
- xorg-libx11
- xorg-libxau
- xorg-libxdmcp
- xorg-libxext
- xorg-libxfixes
- xorg-libxi
- xorg-libxrender
- xorg-libxtst
- xorg-recordproto
- xorg-renderproto
- xorg-xextproto
- xorg-xproto
- xz
- yaml
- zeromq
- zipp
- zlib
- zstd
