name: build

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  render:
    name: build
    runs-on: macOS-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v1
      - uses: r-lib/actions/setup-pandoc@v1
      - uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Configure git
        run: |
          git config --local user.email "noreply@github.com"
          git config --local user.name "GitHub"
          git pull
      - name: Install build dependencies
        run: |
          Rscript -e "install.packages(c('styler','usethis'))"
          python -m pip install --upgrade pip
          pip install snakefmt
      - name: Style R code
        run: |
          Rscript -e 'usethis::use_tidy_style()'
          git add .
          git diff-index --quiet HEAD \
          || git commit \
          --author="github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>" \
          -m 'üé®  Style R code'
      - name: Style Python code
        run: |
          black .
          #snakefmt .
          git add .
          git diff-index --quiet HEAD \
          || git commit \
          --author="github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>" \
          -m 'üé®  Style Python code üêç'
      - name: Push
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.head_ref }}
